#############################################################################
# Makefile for building: satiscalculator
# Generated by qmake (3.1) (Qt 5.15.16)
# Project:  satiscalculator.pro
# Template: app
# Command: C:/msys64/mingw64/bin/qmake.exe -o Makefile satiscalculator.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:/msys64/mingw64/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = C:/msys64/mingw64/bin/qmake.exe -install qinstall
QINSTALL_PROGRAM = C:/msys64/mingw64/bin/qmake.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = widl
ZIP           = 
DEF_FILE      = 
RES_FILE      = 
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: satiscalculator.pro C:/msys64/mingw64/share/qt5/mkspecs/win32-g++/qmake.conf C:/msys64/mingw64/share/qt5/mkspecs/features/spec_pre.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/qdevice.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/features/device_config.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/common/sanitize.conf \
		C:/msys64/mingw64/share/qt5/mkspecs/common/gcc-base.conf \
		C:/msys64/mingw64/share/qt5/mkspecs/common/g++-base.conf \
		C:/msys64/mingw64/share/qt5/mkspecs/common/angle.conf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/common/windows-vulkan.conf \
		C:/msys64/mingw64/share/qt5/mkspecs/common/g++-win32.conf \
		C:/msys64/mingw64/share/qt5/mkspecs/common/windows-desktop.conf \
		C:/msys64/mingw64/share/qt5/mkspecs/qconfig.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_charts.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_core.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_network.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		C:/msys64/mingw64/share/qt5/mkspecs/features/qt_functions.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/qt_config.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/win32-g++/qmake.conf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		C:/msys64/mingw64/share/qt5/mkspecs/features/exclusive_builds.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/toolchain.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/default_pre.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/win32/default_pre.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/resolve_config.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/exclusive_builds_post.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/default_post.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/precompile_header.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/warn_on.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/qt.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/resources_functions.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/resources.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/moc.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/win32/opengl.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/uic.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/qmake_use.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/file_copies.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/win32/windows.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/testcase_targets.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/exceptions.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/yacc.prf \
		C:/msys64/mingw64/share/qt5/mkspecs/features/lex.prf \
		satiscalculator.pro \
		C:/msys64/mingw64/lib/qtmain.prl \
		C:/msys64/mingw64/share/qt5/mkspecs/features/build_pass.prf
	$(QMAKE) -o Makefile satiscalculator.pro
C:/msys64/mingw64/share/qt5/mkspecs/features/spec_pre.prf:
C:/msys64/mingw64/share/qt5/mkspecs/qdevice.pri:
C:/msys64/mingw64/share/qt5/mkspecs/features/device_config.prf:
C:/msys64/mingw64/share/qt5/mkspecs/common/sanitize.conf:
C:/msys64/mingw64/share/qt5/mkspecs/common/gcc-base.conf:
C:/msys64/mingw64/share/qt5/mkspecs/common/g++-base.conf:
C:/msys64/mingw64/share/qt5/mkspecs/common/angle.conf:
C:/msys64/mingw64/share/qt5/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/msys64/mingw64/share/qt5/mkspecs/common/windows-vulkan.conf:
C:/msys64/mingw64/share/qt5/mkspecs/common/g++-win32.conf:
C:/msys64/mingw64/share/qt5/mkspecs/common/windows-desktop.conf:
C:/msys64/mingw64/share/qt5/mkspecs/qconfig.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_charts.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_charts_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_core.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_core_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_gui.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_gui_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_network.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_network_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_printsupport.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qml.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qml_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmltest.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quick.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quick_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_sql.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_sql_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_svg.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_svg_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_testlib.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_virtualkeyboard.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_xml.pri:
C:/msys64/mingw64/share/qt5/mkspecs/modules/qt_lib_xml_private.pri:
C:/msys64/mingw64/share/qt5/mkspecs/features/qt_functions.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/qt_config.prf:
C:/msys64/mingw64/share/qt5/mkspecs/win32-g++/qmake.conf:
C:/msys64/mingw64/share/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
C:/msys64/mingw64/share/qt5/mkspecs/features/exclusive_builds.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/toolchain.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/default_pre.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/win32/default_pre.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/resolve_config.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/exclusive_builds_post.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/default_post.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/precompile_header.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/warn_on.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/qt.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/resources_functions.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/resources.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/moc.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/win32/opengl.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/uic.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/qmake_use.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/file_copies.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/win32/windows.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/testcase_targets.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/exceptions.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/yacc.prf:
C:/msys64/mingw64/share/qt5/mkspecs/features/lex.prf:
satiscalculator.pro:
C:/msys64/mingw64/lib/qtmain.prl:
C:/msys64/mingw64/share/qt5/mkspecs/features/build_pass.prf:
qmake: FORCE
	@$(QMAKE) -o Makefile satiscalculator.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
